In [1]:
pip install numpy

Import Numpy

In [2]:
import numpy as np

Indexing

In [3]:
array_a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [4]:
# Get the row in our case we row at index 0 and 1
array_a[1]

array([ 6,  7,  8,  9, 10])

In [5]:
# Get the row at index 1 column at index 0
array_a[1,0]

np.int64(6)

In [6]:
# we can rewrite the same code in different way
array_a[1][0]

np.int64(6)

In [7]:
#slicing
# get all the values in the row at column index 0
array_a[:,0]

array([1, 6])

Negative index


---



1.   We can use negative index to get the value
2.   we can't use negative zero as there is nothing called Negative zero in Math . sp negative index always starts with -1



In [8]:
array_b = np.array([1,2,3,4,5])

In [9]:
#this will get the last value in a array
array_b[-1]

np.int64(5)

In [10]:
array_b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [11]:
#this will get the last row in a 2d array
array_b[-1]

array([ 6,  7,  8,  9, 10])

In [12]:
# we can also slice with negative index
array_b[:,-1]


array([ 5, 10])

Assigning Values

In [13]:
#we can assign value to a column and row
array_a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array_a[0,0] = 99
array_a

array([[99,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
# this will replace value in the first column in each row
array_a[:,0] = 99
array_a

array([[99,  2,  3,  4,  5],
       [99,  7,  8,  9, 10]])

In [15]:
#entire Row
array_a[0,:] = 99
array_a

array([[99, 99, 99, 99, 99],
       [99,  7,  8,  9, 10]])

In [16]:
#entire Array
array_a[:] = 99
array_a

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [17]:
#assing array to a row
array_a[0,:] = [1,2,3,4,5]
array_a

array([[ 1,  2,  3,  4,  5],
       [99, 99, 99, 99, 99]])

In [18]:
#assign value to fisrt index
array_a[:,0] = [1,2]
array_a

array([[ 1,  2,  3,  4,  5],
       [ 2, 99, 99, 99, 99]])

ElementWise - Elementwise can be used to add the arrays values togethor


In [19]:
array_a = np.array([1,2,3,4,5])
array_b = np.array([[6,7,8,9,10],[11,12,13,14,15]])

In [20]:
# we can subtract / Multiply and divide
array_a = array_a + 2

In [21]:
array_a

array([3, 4, 5, 6, 7])

In [22]:
#we can append two arrays until theier length of the row matched
array_b+array_a

array([[ 9, 11, 13, 15, 17],
       [14, 16, 18, 20, 22]])

In [23]:
array_c = [1,2,3]

In [24]:
#if we try to append arrays with uncommon shape . you will get these following error
#array_b + array_c

ValueError: operands could not be broadcast together with shapes (2,5) (3,) 

datatype - By default numoy will assign the datatype to array which works for all the values

---

URL : https://numpy.org/doc/stable/user/basics.types.html

In [ ]:
#this exmaple resturn U32 which is the dentoin for string
array_a = np.array([1,2.0,"3"])
array_a.dtype

In [ ]:
# We can also set the dtype while initializing an array
array_b = np.array([1,2,3,4],dtype = np.int16)
array_b

In [ ]:
# We can also set the dtype to float even though the values are in INT format
array_b = np.array([1,2,3,4],dtype = np.float64)
array_b