In [1]:
pip install numpy

Import Numpy

In [2]:
import numpy as np

Indexing

In [6]:
array_a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [7]:
# Get the row in our case we row at index 0 and 1
array_a[1]

array([ 6,  7,  8,  9, 10])

In [8]:
# Get the row at index 1 column at index 0
array_a[1,0]

np.int64(6)

In [9]:
# we can rewrite the same code in different way
array_a[1][0]

np.int64(6)

In [10]:
#slicing
# get all the values in the row at column index 0
array_a[:,0]

array([1, 6])

Negative index


---



1.   We can use negative index to get the value
2.   we can't use negative zero as there is nothing called Negative zero in Math . sp negative index always starts with -1



In [11]:
array_b = np.array([1,2,3,4,5])

In [12]:
#this will get the last value in a array
array_b[-1]

np.int64(5)

In [13]:
array_b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [15]:
#this will get the last row in a 2d array
array_b[-1]

array([ 6,  7,  8,  9, 10])

In [16]:
# we can also slice with negative index
array_b[:,-1]


array([ 5, 10])

Assigning Values

In [20]:
#we can assign value to a column and row
array_a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array_a[0,0] = 99
array_a

array([[99,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
# this will replace value in the first column in each row
array_a[:,0] = 99
array_a

array([[99,  2,  3,  4,  5],
       [99,  7,  8,  9, 10]])

In [23]:
#entire Row
array_a[0,:] = 99
array_a

array([[99, 99, 99, 99, 99],
       [99,  7,  8,  9, 10]])

In [25]:
#entire Array
array_a[:] = 99
array_a

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [27]:
#assing array to a row
array_a[0,:] = [1,2,3,4,5]
array_a

array([[ 1,  2,  3,  4,  5],
       [99, 99, 99, 99, 99]])

In [28]:
#assign value to fisrt index
array_a[:,0] = [1,2]
array_a

array([[ 1,  2,  3,  4,  5],
       [ 2, 99, 99, 99, 99]])