slicing

In [11]:
import numpy as np

In [12]:
array_a = np.array([1,2,3,4,5,6,7,8,9,10])
array_b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

Basic Slicing

In [13]:
array_b[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [14]:
array_b[0:0]

array([], shape=(0, 5), dtype=int64)

In [15]:
array_b[0:1]

array([[1, 2, 3, 4, 5]])

In [16]:
array_b[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
#exludes the first row
array_b[:1]

array([[1, 2, 3, 4, 5]])

In [18]:
#exludes the first row
array_b[1:]

array([[ 6,  7,  8,  9, 10]])

In [19]:
array_b[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
array_b[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
#nagative index
array_b[-1:]

array([[ 6,  7,  8,  9, 10]])

In [22]:
array_b[:-1]

array([[1, 2, 3, 4, 5]])

In [23]:
#column slicing
array_b[:,1]

array([2, 7])

In [25]:
array_b[1:,1:]

array([[ 7,  8,  9, 10]])

In [30]:
array_b[0:-1,:-1]

array([[1, 2, 3, 4]])