slicing

In [2]:
import numpy as np

In [3]:
array_a = np.array([1,2,3,4,5,6,7,8,9,10])
array_b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

Basic Slicing

In [4]:
array_b[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
array_b[0:0]

array([], shape=(0, 5), dtype=int64)

In [6]:
array_b[0:1]

array([[1, 2, 3, 4, 5]])

In [7]:
array_b[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
#exludes the first row
array_b[:1]

array([[1, 2, 3, 4, 5]])

In [9]:
#exludes the first row
array_b[1:]

array([[ 6,  7,  8,  9, 10]])

In [10]:
array_b[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
array_b[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
#nagative index
array_b[-1:]

array([[ 6,  7,  8,  9, 10]])

In [13]:
array_b[:-1]

array([[1, 2, 3, 4, 5]])

In [14]:
#column slicing
array_b[:,1]

array([2, 7])

In [15]:
array_b[1:,1:]

array([[ 7,  8,  9, 10]])

In [16]:
array_b[0:-1,:-1]

array([[1, 2, 3, 4]])

Stepwise Slicing - we take values at certian places apart

1.   Step Argument cant be negative
2.   [start:stop:step]



In [17]:
matrix_3row = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [18]:
matrix_3row[::,::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
matrix_3row[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [21]:
#If set step argumanet as negative it starts from the row bottom
matrix_3row[::-2]

array([[11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5]])

In [22]:
#If set step argumanet as negative it starts from the row bottom
matrix_3row[::-2,::-2]

array([[15, 13, 11],
       [ 5,  3,  1]])

In [30]:
matrix_3row[2::-1]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])