<a href="https://colab.research.google.com/github/kaniarasann/numpy/blob/main/02_numply_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

slicing

In [2]:
import numpy as np

In [3]:
array_a = np.array([1,2,3,4,5,6,7,8,9,10])
array_b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

Basic Slicing

In [4]:
array_b[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
array_b[0:0]

array([], shape=(0, 5), dtype=int64)

In [6]:
array_b[0:1]

array([[1, 2, 3, 4, 5]])

In [7]:
array_b[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
#exludes the first row
array_b[:1]

array([[1, 2, 3, 4, 5]])

In [9]:
#exludes the first row
array_b[1:]

array([[ 6,  7,  8,  9, 10]])

In [10]:
array_b[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
array_b[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
#nagative index
array_b[-1:]

array([[ 6,  7,  8,  9, 10]])

In [13]:
array_b[:-1]

array([[1, 2, 3, 4, 5]])

In [14]:
#column slicing
array_b[:,1]

array([2, 7])

In [15]:
array_b[1:,1:]

array([[ 7,  8,  9, 10]])

In [16]:
array_b[0:-1,:-1]

array([[1, 2, 3, 4]])

Stepwise Slicing - we take values at certian places apart

1.   Step Argument cant be negative
2.   [start:stop:step]



In [17]:
matrix_3row = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [18]:
matrix_3row[::,::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
matrix_3row[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [20]:
#If set step argumanet as negative it starts from the row bottom
matrix_3row[::-2]

array([[11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5]])

In [21]:
#If set step argumanet as negative it starts from the row bottom
matrix_3row[::-2,::-2]

array([[15, 13, 11],
       [ 5,  3,  1]])

In [22]:
matrix_3row[2::-1]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

Conditional Slicing

it flattens out the whole array in single dimensional

In [23]:
matrix_c = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [24]:
matrix_c[matrix_c<5]

array([1, 2, 3, 4])

In [25]:
#check in column
matrix_c[:,0]>5

array([False,  True,  True])

In [26]:
#using and condition
matrix_c[(matrix_c%2 == 0) & (matrix_c>5)]

array([ 6,  8, 10, 12, 14])

Squeezing


1.   Slicing and indexing reyurn the same value but their type differs
2.   It can be achieved with the help of executing syntax [].squeeze or np.squeeze([])



In [27]:
matrix_s = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [29]:
res_one = matrix_s[0,0]
res_one

np.int64(1)

In [39]:
res_squeeze_one=matrix_s[0:1,0:1]
print(res_squeeze_one.shape)

(1, 1)


In [41]:
type(np.squeeze(res_squeeze_one))

numpy.ndarray

In [42]:
np.squeeze(matrix_s)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [43]:
res_squeeze_two=matrix_s[0:1,0:2]

In [45]:
res_squeeze_two.squeeze()

array([1, 2])