In [1]:
import numpy as np

Np.Zeros


---


Will generate array with zero values for the given size

In [2]:
array_empty = np.zeros(shape = (2,3))
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


Np.ones

Will generate array with ones values for the given size

In [3]:
array_ones = np.ones(shape = (2,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


Np.fill values

In [4]:
array_fill = np.full(shape = (2,3),fill_value=2)
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


**_like**


---

Like Generates array in similar dimenstion just like copying


In [5]:
array_sample_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_sample_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
empty_array_like = np.empty_like(array_sample_3x3)
print(empty_array_like)

[[285251360         0         0]
 [        0         0         0]
 [        0         0         0]]


In [7]:
zero_array_like = np.zeros_like(array_sample_3x3)
print(zero_array_like)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
ones_array_like = np.ones_like(array_sample_3x3)
print(ones_array_like)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
fill_array_like = np.full_like(array_sample_3x3,fill_value=5)
print(fill_array_like)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


np.arange

1.   range - Generates the ranges as returns a list
2.   arange - Generate array with a range



In [10]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
array_rng = np.arange(1,10)
print(array_rng)

[1 2 3 4 5 6 7 8 9]


In [12]:
array_rng = np.arange(stop=10)
print(array_rng)
#

[0 1 2 3 4 5 6 7 8 9]


In [13]:
array_rng = np.arange(start=1,stop=10,step=2)
print(array_rng)


[1 3 5 7 9]


In [14]:
array_rng = np.arange(start=1,stop=10,step=2.5,dtype=np.float32)
print(array_rng)

[1.  3.5 6.  8.5]


In [15]:
array_rng = np.arange(start=1,stop=10,step=2.5,dtype=np.int32)
print(array_rng)

[1 3 5 7]


Random Generator

In [18]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [20]:
array_rg_one = gen(pcg())
array_rg_one = array_rg_one.normal(size=(5,5))
print(array_rg_one)

[[ 5.65592271e-02 -4.44596786e-01  1.12881796e+00 -6.34990786e-01
  -1.37978383e-01]
 [-3.51318417e-01 -2.98995745e-01  1.20155789e+00  4.61586089e-01
  -1.44132828e+00]
 [-3.81800288e-01 -2.50951066e-01  1.81356999e-01  3.08321477e-01
   2.66236834e-02]
 [-1.59263619e+00 -2.89749806e-01 -2.82693642e-04  7.06804730e-01
  -1.17307889e+00]
 [ 4.35548994e-01 -1.52959793e-01 -5.53582570e-01  3.62873301e-01
   1.04061763e+00]]


In [22]:
array_rng = np.random.normal(size=(5,5))
print(array_rng)

[[-0.13712086  0.26927625  0.87907988  2.28470774 -1.68475651]
 [ 0.26339682 -0.3962005  -0.33524532 -1.88383064  0.77434696]
 [ 0.54464358 -1.10129438  0.14538934 -0.6513704   0.47705524]
 [ 0.16004483  0.27302517 -0.26814488 -1.52600811 -0.58668066]
 [ 0.4036634  -0.47882059 -0.80317055  0.97967869 -0.16777779]]


In [25]:
arry_with_seed = gen(pcg(seed=365))
arry_with_seed = arry_with_seed.normal(size=(5,5))
print(arry_with_seed)

[[-0.13640899  0.09414431 -0.06300442  1.05391641 -0.6866818 ]
 [-0.50922173 -0.7999526   0.73041825  0.08825439 -2.1177576 ]
 [ 0.65526774 -0.48095012 -0.5519114  -0.58578662 -0.98257896]
 [ 1.12378166 -1.30984316 -0.04703774  0.955272    0.26071745]
 [-0.20023668 -1.50172484 -1.4929163   0.96535084  1.18694633]]


In [31]:
np.random.seed(365)
array_random = np.random.rand(5,5)
print(array_random)

[[0.94145574 0.64160271 0.68461047 0.58856207 0.54388722]
 [0.36807091 0.76662577 0.30501243 0.44208597 0.11044334]
 [0.43837379 0.7526158  0.29162625 0.88572275 0.99669126]
 [0.48656838 0.34941019 0.15141276 0.89194761 0.77354254]
 [0.78021392 0.48900035 0.53286284 0.18985509 0.95855187]]


Random Integers

In [33]:
array_rdm_int = np.random.randint(10,size=(5,5))
print(array_rdm_int)

[[7 9 2 6 6]
 [3 7 7 1 7]
 [0 2 5 2 6]
 [9 7 9 7 4]
 [7 9 4 3 0]]


In [37]:
#between low and highs
array_rg_one = gen(pcg(seed=365))
array_rg_one = array_rg_one.integers(low = 10,high = 100,size=(5,5))
print(array_rg_one)

[[18 78 64 78 84]
 [66 67 28 10 69]
 [45 15 37 74 96]
 [19 21 89 73 54]
 [53 84 66 51 92]]


In [40]:
# to generate array in the given choice
array_rg_choice = gen(pcg(seed=365))
array_rg_choice.choice([1,2,3,4,5],size=(5,5))

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [43]:
#to generate arrat with given propnaliity
array_rg_choice = gen(pcg(seed=365))
array_rg_choice.choice([1,2,3,4,5],p=[0.1,0.2,0.1,0.4,0.2],size=(5,5))

array([[4, 4, 4, 2, 4],
       [1, 4, 2, 5, 4],
       [5, 4, 1, 4, 3],
       [2, 4, 4, 4, 4],
       [4, 1, 4, 5, 2]])