In [1]:
import numpy as np

Np.Zeros


---


Will generate array with zero values for the given size

In [2]:
array_empty = np.zeros(shape = (2,3))
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


Np.ones

Will generate array with ones values for the given size

In [3]:
array_ones = np.ones(shape = (2,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


Np.fill values

In [4]:
array_fill = np.full(shape = (2,3),fill_value=2)
print(array_empty)

[[0. 0. 0.]
 [0. 0. 0.]]


**_like**


---

Like Generates array in similar dimenstion just like copying


In [5]:
array_sample_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_sample_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
empty_array_like = np.empty_like(array_sample_3x3)
print(empty_array_like)

[[705797791         0         0]
 [        0         0         0]
 [        0         0         0]]


In [7]:
zero_array_like = np.zeros_like(array_sample_3x3)
print(zero_array_like)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
ones_array_like = np.ones_like(array_sample_3x3)
print(ones_array_like)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [9]:
fill_array_like = np.full_like(array_sample_3x3,fill_value=5)
print(fill_array_like)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


np.arange

1.   range - Generates the ranges as returns a list
2.   arange - Generate array with a range



In [10]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
array_rng = np.arange(1,10)
print(array_rng)

[1 2 3 4 5 6 7 8 9]


In [12]:
array_rng = np.arange(stop=10)
print(array_rng)
#

[0 1 2 3 4 5 6 7 8 9]


In [13]:
array_rng = np.arange(start=1,stop=10,step=2)
print(array_rng)


[1 3 5 7 9]


In [16]:
array_rng = np.arange(start=1,stop=10,step=2.5,dtype=np.float32)
print(array_rng)

[1.  3.5 6.  8.5]


In [17]:
array_rng = np.arange(start=1,stop=10,step=2.5,dtype=np.int32)
print(array_rng)

[1 3 5 7]
